on: [push]
jobs:
   Build:
    name: FirstBuild
    runs-on: windows-latest
    steps:
    - name: Setup_Nodejs
      uses: actions/checkout@v2
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: latest
    - name: Install Live Server
      run: npm install -g live-server
    - name: Run Live Server using npx
      run: npx live-server
    - name: Build and Run the app
      run: |
       git clone https://github.com/AlessioLopardo-EDU/UNESCOTRACKER
       npm install
       npm run build
