name: Test1

on: [push]

jobs:
  Build:
    name: FirstBuild
    runs-on: windows-latest

    steps:
      - name: Checkout2
        uses: actions/checkout@v4
        with:
          node-version: 'latest'
      
      # Étape pour supprimer la branche "Test"
      - name: Delete branch 'Test'
        run: git push origin --delete Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

