name: Test1

on: [push]

jobs:
  Build:
    name: FirstBuild
    runs-on: windows-latest

    steps:
      - name: Checkout2
        uses: actions/checkout@v4
        with:
          node-version: 20.8.1
      - run: git checkout -b "Test2"
